### PR TITLE
Fix broken BloodHound installation

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request adds some code to work around some OpenSSL errors that arise when building BloodHound with a newer version of Node.

## 💭 Motivation and context ##

This AMI cannot be built without this fix.

## 🧪 Testing ##

All automated tests pass.  I also built a testing AMI with these changes and verified that I was able to start `BloodHound`, albeit with the `--disable-gpu-sandbox` flag.  I believe this flag is currently required because [of a buggy interaction between `electron` and a new version of `glibc`](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468).

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a release.

### CODE REVIEW

**Comment by jsf9k** [comment]
@m1j09830, do you currently run `BloodHound` with the `--disable-gpu-sandbox` flag?  This is the only way I am able to get the most recent build of that tool to run in Kali.  I believe [this is due to an interaction between `electron` and a new version of `glibc`](https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468).

Is adding the `---disable-gpu-sandbox` an OK workaround until the bug is fixed upstream?

**Comment by m1j09830** [comment]
Hey @jsf9k we don't currently have to run it with the `--disable-gpu-sandbox` flag but if it won't work without it I'm fine with us running it until the bug is fixed. I'm also good with us using the last known good version if that ends up being easier as well.

**Comment by jsf9k** [comment]
> Hey @jsf9k we don't currently have to run it with the `--disable-gpu-sandbox` flag but if it won't work without it I'm fine with us running it until the bug is fixed. I'm also good with us using the last known good version if that ends up being easier as well.

I used to install BloodHound via the Kali Linux package, but then I was told that assessments needs the very latest version of the tool.  As a result I don't have a "last known good version", it's just whatever was in the `master` branch the last time I built the AMI.

**Review by dav3r — APPROVED** [review]
Thanks for getting this all sorted out! 🔎

**Review by mcdonnnj — APPROVED** [review]
Thanks for hunting this down. 👍

**Pull request merged**
