### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-packer.git`](https://github.com/cisagov/skeleton-packer.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

---

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

## ✅ Pre-merge checklist ##

- [x] Revert dependencies to default branches.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]

**Comment by jsf9k** [comment]
I will fix the broken [cisagov/ansible-role-xfce-cool](https://github.com/cisagov/ansible-role-xfce-cool) Ansible role.

**Comment by mcdonnnj** [comment]
Just for anyone else stumbling in here: This is now breaking because of an issue with installing BloodHound dependencies.

**Comment by jsf9k** [comment]
It builds once again!  Huzzah!

**Review by dav3r — APPROVED** [review]
image

Do we want to mark this PR as "blocked" until https://github.com/cisagov/ansible-role-cobalt-strike/pull/55 is merged and also add a reminder checkbox to revert https://github.com/cisagov/kali-packer/pull/107/commits/5c86bfc5595c4078156745f289a9de3d6d83db84 before we merge this PR?

**Comment by jsf9k** [comment]
Don't forget to revert commit 5c86bfc5595c4078156745f289a9de3d6d83db84 before merging this PR!

**Comment by jsf9k** [comment]
@mcdonnnj, this one is finally ready for review when you have time.

**Review by mcdonnnj — APPROVED** [review]
🚀🌕

**Pull request merged**
