### PR TITLE
License Burp Suite Pro for the vnc user

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request makes the change of licensing Burp Suite Pro for the `vnc` user.

## 💭 Motivation and Context ##

See cisagov/ansible-role-burp-suite-pro#5.

## 🧪 Testing ##

I built a staging AMI with this code and verified on env0 of our staging COOL environment that Burp Suite Pro is now pre-licensed.

## ✅ Pre-approval checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.
* [x] Build a staging AMI
* [x] Test staging AMI

## ✅ Post-approval checklist ##
* [x] Revert back to the `develop` branch of [cisagov/ansible-role-burp-suite-pro](https://github.com/cisagov/ansible-role-burp-suite-pro) once cisagov/ansible-role-burp-suite-pro#5 is merged.
* [x] Finalize version

## ✅ Post-merge checklist ##
* [ ] Build a production AMI

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Good stuff! 👍

**Review by hillaryj — APPROVED** [review]
🏆 

As a point of order, should the checklist items in the PR that occur after merging go in the associated issue instead? We'd talked before about wanting all the boxes to be checked to consider a PR ready to review.

**Comment by jsf9k** [comment]
> As a point of order, should the checklist items in the PR that occur after merging go in the associated issue instead? We'd talked before about wanting all the boxes to be checked to consider a PR ready to review.

I remember talking about that.  The problem with putting them in the associated issue is that it makes it vastly easier to forget to do them - that's why i like them being here.

As an alternative, what if I created separate sections titled "Post-approval checklist" and "Post-merge checklist" and put those checkboxes there?  As an example I went ahead and did that with this PR.  Those sections won't normally be required, except in the case of these `*-packer` repos.

**Comment by dav3r** [comment]
I am good with adding these "Post-approval" and "Post-merge" checklists where needed.  We could add them to the template and leave them blank with a comment asking the PR creator to add those items if necessary.

**Comment by jsf9k** [comment]
> I am good with adding these "Post-approval" and "Post-merge" checklists where needed. We could add them to the template and leave them blank with a comment asking the PR creator to add those items if necessary.

We should probably rename "Checklist" to "Pre-approval checklist" in that case.

**Review by mcdonnnj — APPROVED** [review]
Glad you found the solution ✔

**Pull request merged**
